(define (domain narrative-domain)
      (:requirements :strips :typing)
      (:types character location object obstacle - thing)
      (:predicates 
        (at ?c - character ?l - location)
        (has ?c - character ?o - object)
        (connected ?l1 - location ?l2 - location)
        (at-obj ?o - object ?l - location)
        (visited ?l - location)
        (locked ?l - location)
        (key-for ?o - object ?l - location)
        (obstacle-active ?obs - obstacle)
        (obstacle-solved ?obs - obstacle)
        (quest-complete)
      )
      (:action move
        :parameters (?c - character ?from - location ?to - location)
        :precondition (and (at ?c ?from) (connected ?from ?to) (not (locked ?to)))
        :effect (and (not (at ?c ?from)) (at ?c ?to) (visited ?to))
      )
      (:action take
        :parameters (?c - character ?o - object ?l - location)
        :precondition (and (at ?c ?l) (at-obj ?o ?l))
        :effect (and (has ?c ?o) (not (at-obj ?o ?l)))
      )
      (:action unlock
        :parameters (?c - character ?k - object ?loc - location)
        :precondition (and (has ?c ?k) (key-for ?k ?loc))
        :effect (and (not (locked ?loc)))
      )
      (:action solve-obstacle
        :parameters (?c - character ?obs - obstacle ?req - object)
        :precondition (and (at ?c ?l) (obstacle-active ?obs))
        :effect (and (obstacle-solved ?obs) (not (obstacle-active ?obs)))
      )
      (:action use
        :parameters (?c - character ?o - object ?l - location)
        :precondition (and (at ?c ?l) (has ?c ?o))
        :effect (and (not (has ?c ?o)) (quest-complete))
      )
      (:action interact
        :parameters (?c1 - character ?c2 - character)
        :precondition (and (at ?c1 ?l) (at ?c2 ?l))
        :effect (and)
      )
      (:action unlock-location
        :parameters (?c - character ?k - object ?loc - location)
        :precondition (and (has ?c ?k) (key-for ?k ?loc) (locked ?loc))
        :effect (and (not (locked ?loc)))
      )
    )