(define (problem narrative-problem)
  (:domain narrative-domain)
  (:objects
    minimum rival obstacles - character
    entrance corridor chamber vault exit - location
    code key system - object
  )
    (:init
    (at minimum entrance)
    (connected entrance corridor)
    (at-obj code corridor)
    (visited entrance)
    (connected entrance corridor)
    (connected corridor chamber)
    (connected chamber vault)
    (connected vault exit)
    (at minimum entrance)
    (at rival entrance)
    (at obstacles corridor)
    (at system corridor)
    (at key corridor)
    (connected entrance chamber)
    (connected entrance exit)
    (connected vault corridor)
    (connected vault entrance)
    (connected chamber exit)
    (connected exit corridor)
    (connected chamber corridor)
    (connected exit chamber)
    (connected corridor vault)
    (connected exit entrance)
    (connected exit vault)
    (connected entrance vault)
    (connected corridor entrance)
    (connected vault chamber)
    (connected corridor exit)
    (connected chamber entrance)
  )
  (:goal (and
    (at minimum exit)
    (has minimum code)
  ))
)